In [8]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:

docs = ['additional income',
		    'best price',
        'big bucks',
        'cash bonus',
        'earn extra cash',
        'spring savings certificate',
        'valero gas marketing',
        'all domestic employees',
        'nominations for oct',
        'confirmation from spinner']

labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [10]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[27, 23], [10, 29], [17, 32], [41, 37], [17, 4, 41], [14, 9, 7], [13, 29, 23], [39, 13, 3], [25, 39, 15], [31, 40, 14]]


In [11]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[27 23  0  0]
 [10 29  0  0]
 [17 32  0  0]
 [41 37  0  0]
 [17  4 41  0]
 [14  9  7  0]
 [13 29 23  0]
 [39 13  3  0]
 [25 39 15  0]
 [31 40 14  0]]


In [12]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [13]:
model.fit(padded_docs, labels, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('정확도=',accuracy)

정확도= 1.0


In [14]:
test_doc = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')

print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
[[0.56520504]]
